### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by alainsch** [thomasddn/home-assistant-addons#2]
Hello,

I'm probably missing some important thing here, but I couldn't get it to work.

My CTD02E is in the same network as my home assistant. 

I installed Mosquitto, QBUS MQTT Gateway and QBHA.
Mosquitto is up-and-running and I have the MQTT integration in my devices.

I did not specify any config options for QBUS MQTT Gateway, sa that it will use the installed Mosquitto add-on. When I start the gateway, I see some errors

I20240515 15:16:25.438364   126 MainApp.cpp:60] UbieLite (UbieLite, May 18 2022, 17:04:53)
I20240515 15:16:25.438706   126 MainApp.cpp:61] ==========================================
I20240515 15:16:25.439112   126 InterComm.cpp:140] (Main) createMailbox: Main
I20240515 15:16:25.439507   126 InterComm.cpp:183] Mailbox: Main, is using a robuust mutex: true, Boost version: 1_58
I20240515 15:16:25.440094   126 IoServicePool.cpp:121] IoService pool 'RenRem' created with poolsize: 1
E20240515 15:16:25.451880   126 ConfigManager.cpp:896] Unable to open file: '/opt/qbus/fullconfig.json'
I20240515 15:16:25.452339   126 MainApp.cpp:95] Connecting via MQTT, host: tcp://core-mosquitto:1883, user: addons
I20240515 15:16:25.453377   126 MqttConnector.cpp:131] Using libmosquitto: 1.6.7
W20240515 15:16:25.457136   126 MqttCmdRouter.cpp:89] SSH User unknown, not creating SSH Tunnel manager
I20240515 15:16:25.457417   126 MqttConnector.cpp:273] Connecting via Username/Pwd
I20240515 15:16:25.458086   126 MqttConnector.cpp:297] Connecting with server: core-mosquitto, port: 1883
I20240515 15:16:25.462303   126 UbieSdk.cpp:86] Creating UbieSDK for: UbieLite
I20240515 15:16:25.462381   126 UbieSdk.cpp:87] Sdk Settings: AppName: UbieLite, InterComm: UbieLite, IdPrefix: UL, MainId: Main, LogicId: , Minimal Sdk: false
I20240515 15:16:25.462425   126 UbieSdk.cpp:103] No UbieSdkStorageIf provided, creating a local one
I20240515 15:16:25.462471   126 SdkPrivateConfig.cpp:28] Using private config file: /opt/qbus/sdkconfig.json
E20240515 15:16:25.462579   126 Utilities.cpp:441] Unable to read file: /opt/qbus/sdkconfig.json
W20240515 15:16:25.462630   126 SdkPrivateConfig.cpp:160] Private config file does not exists: /opt/qbus/sdkconfig.json
I20240515 15:16:25.463320   136 Cli.cpp:188] Starting CLI on port: 5000
I20240515 15:16:25.464123   126 InterComm.cpp:140] (UbieLite) createMailbox: UbieLite
I20240515 15:16:25.465044   126 InterComm.cpp:183] Mailbox: UbieLite, is using a robuust mutex: true, Boost version: 1_58
I20240515 15:16:25.465374   126 InterComm.cpp:201] (UbieLite) registerMailbox: Main
I20240515 15:16:25.465704   126 UbieSdk.cpp:140] Watchdog nog enabled
E20240515 15:16:25.467734   126 AlarmSource.cpp:67] Translation file not found: /opt/qbus/messages.json
E20240515 15:16:25.469272   126 FileStorage.cpp:502] Failed to open file: /opt/qbus/qbushw.json
I20240515 15:16:25.469573   126 FileStorage.cpp:518] Config read, controllers found: 0
I20240515 15:16:25.471369   126 IoServicePool.cpp:121] IoService pool 'Main' created with poolsize: 2
I20240515 15:16:25.473240   126 IoServicePool.cpp:121] IoService pool 'Config' created with poolsize: 2
I20240515 15:16:25.474409   126 IoServicePool.cpp:121] IoService pool 'LogPlayer' created with poolsize: 2
I20240515 15:16:25.475458   126 QbusMain.cpp:207] Using Sdk version: 1.0.5
I20240515 15:16:25.475663   126 UbieSdk.cpp:243] Register UbieSdkClient
I20240515 15:16:25.475704   126 ConfigClient.cpp:66] RequestConfig, sectionname: application.ubielite
I20240515 15:16:25.483246   129 StatusReceiver.cpp:300] StatusSender 'UbieLite' has registered, requesting all FB id's
I20240515 15:16:25.484445   129 InterComm.cpp:201] (Main) registerMailbox: UbieLite
I20240515 15:16:25.486590   129 ConfigManager.cpp:471] Storing config monitor for destination: UbieLite, sectionname: 'application.ubielite'
I20240515 15:16:25.486753   129 ConfigManager.cpp:798] Sendig configsection: 'application.ubielite', to destination: UbieLite
E20240515 15:16:25.486793   129 ConfigHelper.cpp:163] Section 'application' is not a valid section in the config
W20240515 15:16:25.489176   129 MqttRouter.cpp:656] Config not send, MQTT Offline
I20240515 15:16:25.764143   135 MqttConnector.cpp:433] MQTT Connected: success
I20240515 15:16:25.764220   135 MqttRouter.cpp:157] MQTT broker connected
I20240515 15:16:25.965092   134 MqttRouter.cpp:1509] Sending Online to MQTT: {"id":"QBUSMQTTGW","online":true,"reason":"Connected @2024-05-15-15:16:25"}
I20240515 15:16:25.965251   134 ConfigManager.cpp:117] Cloud connected
I20240515 15:16:30.479938   140 FileStorage.cpp:534] Saving controller info to file: /opt/qbus/qbushw.json
I20240515 15:16:30.535410   140 QbusMain.cpp:540] Creating controller, id: 1,  serial: 002663
I20240515 15:16:30.535547   129 ConfigManager.cpp:947] Store private config to file: /ubieroot/configbackup/UbieLite_2024-05-15-15-16.json
I20240515 15:16:30.546125   141 ActiveController.cpp:286] [UL1] Currently offline

Did I missed some required configuration work? How can QBUS MQTT Gateway now where to find my CTD02E controller?

Thx

**Comment by alainsch** [comment]
nivermind... Found the qbusforum.be forum and the explanation.

**Comment by thomasddn** [comment]
Hi @alainsch! I'm glad you found the solution. Can you post here what you exactly did to fix it? So other people with the same issue might find the solution faster, and maybe I can update the documentation based on your response.

**Comment by alainsch** [comment]
I probably started the two plugins in the wrong order. 

I started QBus MQTT Gateway before QBHA. When I restarted the MQTT Gateway while QBHA was still running, I noticed that my controller was detected and the QBus entity was generated in MQTT.

Is there a technical reason you decided to create a single QBUS device with an qbus entity (light/cover/...) an entity in that device? Now 1 see 1 device in MQTT with a lot of entities.

I also use Zigbee2MQTT for my Zigbee devices and there every light/cover/... is a separate device. So for Zigbee, I see (in my case) 49 devices.

**Comment by thomasddn** [comment]
Which benefit would you have if every light/cover/climate/sensor/... would be a different device?

**Comment by alainsch** [comment]
I think it follows more the Home Assistant logic.

I have 49 zigbee devices, MQTT shows 49 devices, not 1 device with 49 entities.
I have 33 ESPHome devices, ESPHome shows 33 devices, not 1 device with 33 entities
I have 4 Shelly devices, 2 Sonos devices, 2 devolo devices, all integrations showing multiple devices.

In my opinion, QBus is an eco-system, just like Zigbee, ESPHome, Shelly, Airzone, Sonos, ... All those eco-systems choose to have one device per logical unit.

**Comment by alainsch** [comment]
After some further experimentation, I understand the difference in setup.

With Zigbee/Shelly/ESPHome devices, we immediately see all the properties of the devices as well. For example, with Switch devices we see both the status of the output (the lamp?) and the input (the switch?), because based on the events on the input we should be able to do something with the output: “If switch SW_GANG_1 is pressed, toggle lamp LG_GANG_1”.

Here at QBUS you only see the outputs and the spheres. So you can trigger things from HA, but you know little (nothing?) what happens within QBUS on the switches, unless I missed something.

So I see in HA all my lights, shutters, thermostats, spheres, but no switches.

Unless this is something with those binary sensors in the QBHA config, but I haven't figured that out yet.

**Comment by thomasddn** [comment]
Your last comment is correct. The binary sensors config is meant to add certain Qbus switch outputs as a binary sensor to HA. In my setup I have this configured for my kettle, magnet sensor and light sensor. I don't want to be able to toggle my kettle with HA, because that is already handled with logic in Qbus. The sensors are connected to an input module, so there is no way you can toggle those, but Qbus exposes those as "on/off".

I'm closing the issue now. If you want to further discuss, let me know, then I'll open up the GitHub Discussions feature.
